Update script/bootstrap to detect Vagrant version.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -26,12 +26,21 @@ if ! command -v bundle >/dev/null ; then
   gem install bundler
 fi
 
-if ! bundle check >/dev/null ; then
-  bundle_cmd="bundle install --path vendor/bundle --binstubs vendor/binstubs"
-  banner "Running '$bundle_cmd'"
-  $bundle_cmd
-else
-  log "Bundler up to date, skipping 'bundle install'"
+bundle_cmd="bundle install --path vendor/bundle --binstubs vendor/binstubs"
+banner "Running '$bundle_cmd'"
+$bundle_cmd
+bundle clean
+
+if ! command -v vagrant >/dev/null ; then
+  fail "An installation of Vagrant could not be found, please install a package"
+fi
+
+if [[ "$(vagrant --version)" < "Vagrant version 1.1.0" ]] ; then
+  fail "Only Vagrant versions 1.1.0 and up are supported, please update"
+fi
+
+if ! vagrant plugin list | grep -q '^berkshelf-vagrant ' >/dev/null ; then
+  fail "Berkshelf Vagrant must be installed with: vagrant install berkshelf-plugin"
 fi
 
 banner "Running 'berks install'"
