Update script/bootstrap.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,33 +1,41 @@
 #!/usr/bin/env bash
+set -e
+[ -n "$BOOTSTRAP_DEBUG" ] && set -x
 
-log()   { printf -- "-----> $*\n" ; return $? ; }
-warn()  { printf -- ">>> $*\n" ; return $? ; }
-fail()  { printf -- "\nERROR: $*\n" ; exit 1 ; }
+banner()  { printf -- "-----> $*\n"; }
+log()     { printf -- "       $*\n"; }
+warn()    { printf -- ">>>>>> $*\n"; }
+fail()    { printf -- "\nERROR: $*\n" ; exit 1 ; }
 
 if ! command -v direnv >/dev/null ; then
-  if [ "$(uname)" == "Darwin" ] && command -v brew >/dev/null ; then
-    log "Direnv package missing, installing from homebrew"
-    brew install direnv
-    eval $(direnv hook $SHELL)
-  else
-    warn "The direnv command is not installed and helps in configuring"
-    warn "this Chef repository."
-    warn ""
-    warn "Please visit https://github.com/zimbatm/direnv for more details."
-  fi
+  warn "the direnv command is not installed and helps in using"
+  warn "this project."
+  warn ""
+  warn "please visit https://github.com/zimbatm/direnv for more details."
+  warn ""
+  warn "if you are on a mac and using homebrew, install it with:"
+  warn ""
+  warn "    $ brew install direnv"
+  warn ""
+  warn "follow the post-install instructions, and re-run $0"
+  warn "\n"
 fi
 
+
 if ! command -v bundle >/dev/null ; then
-  log "Installing bundler gem"
+  banner "Installing bundler gem"
   gem install bundler
 fi
 
 if ! bundle check >/dev/null ; then
-  log "Running bundle"
-  bundle install --binstubs --path vendor/bundle
+  bundle_cmd="bundle install --path vendor/bundle --binstubs vendor/binstubs"
+  banner "Running '$bundle_cmd'"
+  $bundle_cmd
 else
-  log "Bundler up to date, skipping bundle install"
+  log "Bundler up to date, skipping 'bundle install'"
 fi
 
-log "Running Berkshelf"
-"$(dirname $0)/../bin/berks" install
+banner "Running 'berks install'"
+"$(dirname $0)/../vendor/binstubs/berks" install
+
+banner 'All ready!'
